name: Library-Catalog

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Npm install
        run: npm install
      - name: Install playwright test library
        run: npm install -D @playwright/test
      - name: Start frontend
        run: npm run start &
      - name: Navigate to server folder
        run: cd Library-Catalog/server/
      - name: Start backend
        run: node server.js
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Playwright tests
        run: npx playwright test tests/ui.test.js
